# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode11.4
language: swift
# cache: cocoapods

xcode_workspace: Example/emojidataios.xcworkspace
xcode_scheme: emojidataios
xcode_destination: platform=iOS Simulator,OS=13.4,name=iPhone 11
podfile: Example/Podfile
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod repo update
  - pod install --project-directory=Example
script:
  #- set -o pipefail && xcodebuild test -workspace Example/emojidataios.xcworkspace -scheme emojidataios-Example -sdk iphonesimulator10.3 -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
  - pod lib lint
  - xcodebuild test -workspace Example/emojidataios.xcworkspace -scheme emojidataios-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
